package com.lt.css.shiftShp.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AbstractEmpTable extends VerticalLayout {
    private VerticalSplitPanel shiftPanel;
    private Grid<com.lt.css.shiftShp.entity.EmployeeDto> fromShiftShp;
    private Grid<com.lt.css.shiftShp.entity.EmployeeDto> toShiftShp;

    public AbstractEmpTable() {
        Design.read(this);
    }

    public VerticalSplitPanel getShiftPanel() {
        return shiftPanel;
    }

    public Grid<com.lt.css.shiftShp.entity.EmployeeDto> getFromShiftShp() {
        return fromShiftShp;
    }

    public Grid<com.lt.css.shiftShp.entity.EmployeeDto> getToShiftShp() {
        return toShiftShp;
    }

}
